### ISSUE TITLE
vue front

### ISSUE THREAD

**Issue by vouill** [syouon/office-helper#4]
If you want to dev a vue app, the easiest way for you to do it is use vue-cli.
Use `vue init webpack ...` it s the best template for a project.

Just ditch gulp, you are making things much harder to work with, webpack does a lot of stuff for you so you dont have to reinvent the wheel as you so often do @3ck0o . More over you dont have to know how it works to dev. if you need to something with it first refer to the vue-cli template wiki or readme.
If you dont find anything, ping me.

And @3ck0o check [that shit out](https://github.com/yuche/vue-strap) and [this too](https://github.com/vouill/vue-slideout)

**Comment by 3ck0o** [comment]
@vouill Wow, are you sponsored by webpack ? 
Your input has been duly noted, thank you for your participation 👍 
Please consider using the PR tool if you truly want to be involved in the project. Thank you :kissing_heart:
